export const COLUMNS = [
    { id: 0, name: 'Session ID', tdef: 'sessionId', type: 'Select all'},
    { id: 1, name: 'PCKNO', tdef: 'packetNo', type: 'Select all'},
    { id: 2, name: 'FNO', tdef: 'frameNo', type: 'Select all'},
    { id: 3, name: 'PID(Hex)', tdef: 'pidHex', type: 'Select all'},
    { id: 4, name: 'PID(Dec)', tdef: 'pidDec', type: 'Select all'},
    { id: 5, name: 'PID Name', tdef: 'pidName', type: 'Select all'},
    { id: 6, name: 'P[0]', tdef: 'p0Val', type: 'Select all'},
    { id: 7, name: 'P[0] Name', tdef: 'p0Name', type: 'Select all'},
    { id: 8, name: 'P[1]', tdef: 'p1Val', type: 'Select all'},
    { id: 9, name: 'P[1] Name', tdef: 'p1Name', type: 'Select all'},
    { id: 10, name: 'P[2]', tdef: 'p2Val', type: 'Select all'},
    { id: 11, name: 'P[2] Name', tdef: 'p2Name', type: 'Select all'},
    { id: 12, name: 'P[3]', tdef: 'p3Val', type: 'Select all'},
    { id: 13, name: 'P[3] Name', tdef: 'p3Name', type: 'Select all'},
    { id: 14, name: 'P[4]', tdef: 'p4Val', type: 'Select all'},
    { id: 15, name: 'P[4] Name', tdef: 'p4Name', type: 'Select all'},
    { id: 16, name: 'P[5]', tdef: 'p5Val', type: 'Select all'},
    { id: 17, name: 'P[5] Name', tdef: 'p5Name', type: 'Select all'},
    { id: 18, name: 'P[6]', tdef: 'p6Val', type: 'Select all'},
    { id: 19, name: 'P[6] Name', tdef: 'p6Name', type: 'Select all'},
    { id: 20, name: 'P[7]', tdef: 'p7Val', type: 'Select all'},
    { id: 21, name: 'P[7] Name', tdef: 'p7Name', type: 'Select all'},
  ];